### ISSUE TITLE
unable to build kubernetes objects from release manifest: [resource mapping not found for name: "kubescape-scheduler" namespace: "kubescape" from "": no matches for kind "CronJob" in version "batch/v1"

### ISSUE THREAD

**Issue by chinmaydhawale** [kubescape/helm-charts#111]
uccessfully ran following 2 commands - 
helm repo add kubescape https://kubescape.github.io/helm-charts/
helm repo update

However, I'm receiving following error, while installing kubescape. K8 version I'm using is 1.20.7. 

Command I'm executing via PowerSHell in Azure Cluster - 
helm upgrade --install kubescape kubescape/kubescape-cloud-operator -n kubescape --create-namespace --set account=myaccountid --set clusterName=`kubectl config current-context` 

Release "kubescape" does not exist. Installing it now.
 Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "kubescape-scheduler" namespace: "kubescape" from "": no matches for kind "CronJob" in version "batch/v1"
 ensure CRDs are installed first, resource mapping not found for name: "kubevuln-scheduler" namespace: "kubescape" from "": no matches for kind "CronJob" in version "batch/v1"
 ensure CRDs are installed first]

**Comment by craigbox** [comment]
The Helm chart is trying to create a `CronJob` object.  Those went GA, i.e. [`batch/v1` API types were created](https://kubernetes.io/blog/2021/04/09/kubernetes-release-1.21-cronjob-ga/), in Kubernetes v1.21.  You said you're running v1.20.x.  That will be your problem!

I'll add an issue suggesting that the chart should tell you what the required version is, and give a more obvious error if you're running something older than that.
