### ISSUE TITLE
Non-obvious error when trying to install Helm chart into old Kubernetes cluster.

### ISSUE THREAD

**Issue by craigbox** [kubescape/helm-charts#112]
In #111, a user attempted to install the Kubescape Helm chart into a Kubernetes 1.20 cluster.  

Our chart tries to create `batch/v1/CronJob` objects, which only exist in Kubernetes 1.21 and up.

We should (a) keep track of the earliest supported Kubernetes version, and (b) provide an obvious error when someone tries to install the chart into a cluster that is older than that version.

**Comment by XDRAGON2002** [comment]
@craigbox Helm allows two inbuild objects for this specific usecase:
1. `Capabilities.APIVersions.Has $version` indicates whether a version (e.g., `batch/v1`) or resource (e.g., `apps/v1/Deployment`) is available on the cluster.
2. `Capabilities.KubeVersion` and `Capabilities.KubeVersion.Version` is the Kubernetes version.

Which approach should be preferred here? As if we want to ensure that a specific resource version is available in the cluster the first approach is better and direct.

**Comment by craigbox** [comment]
I'd go for the first based on what you've said.
