### ISSUE TITLE
Rendering error in components diagram

### ISSUE THREAD

**Issue by nitishchauhan0022** [kubescape/helm-charts#165]
# Description
The [Operator Component Diagram](https://github.com/kubescape/helm-charts/blob/master/charts/kubescape-cloud-operator/README.md#operator) and several other component diagram at https://github.com/kubescape/helm-charts/blob/master/charts/kubescape-cloud-operator/README.md are not rendering.
![image](https://github.com/kubescape/helm-charts/assets/72253189/9004b85b-a01b-4556-a7cd-4abbac24ca5f)

# Environment
OS: ` ` 
Version: ` ` 
 
# Steps To Reproduce

# Expected behavior
It should be rendered properly like the others. The issue appears to be with the rendering of diagrams within the &lt;details> tag. Moving the declaration of the diagrams outside the &lt;details> tag seems to resolve the rendering issue.
# Actual Behavior

# Additional context

**Comment by dwertent** [comment]
Thank you.
Has been  fixed
