### ISSUE TITLE
Move Kubescape components to use distroless base images

### ISSUE THREAD

**Issue by slashben** [kubescape/helm-charts#241]
## Overview
Kubescape containers are Alpine based. This is not a good security practice and since all of them are Go based apps it wouldn't be very hard to move them to distroless release.

**Comment by Shreya111111** [comment]
@slashben kindly assign this issue to me

**Comment by slashben** [comment]
@Shreya111111 we need to build two images for every component, one distroless for production and one Alpine based for debugging

**Comment by dwertent** [comment]
This is already in validation phase #256
