### ISSUE TITLE
Fix notes.txt

### ISSUE THREAD

**Issue by craigbox** [kubescape/helm-charts#290]
> You can see and change the values of **your** recurring configurations daily scan **at** the following link:
> https://cloud.armosec.io/...

> You can see and change the values of **your** recurring images daily scan **at** the following link:
> https://cloud.armosec.io/...

Please fix typos and remove the ARMO links.

**Comment by craigbox** [comment]
(See also Su-Lyn's suggested changes [here](https://github.com/kubescape/helm-charts/pull/261))

**Comment by dwertent** [comment]
@vladklokun Please update the notes so they will include getting the summary objects.

**Comment by vladklokun** [comment]
@dwertent Will do.
