### ISSUE TITLE
Problem with upgrading to v1.16.1(7)

### ISSUE THREAD

**Issue by batazor** [kubescape/helm-charts#331]
I had a prolem with upgrading to 1.16.1(2) version:

```
{"level":"info","ts":"2023-11-02T13:30:39Z","msg":"credentials loaded","accessKeyLength":0,"accountLength":36}
{"level":"info","ts":"2023-11-02T13:30:39Z","msg":"keepLocal config is true, statuses and scan reports won't be sent to Armo cloud"}
{"level":"info","ts":"2023-11-02T13:30:39Z","msg":"starting server"}
{"level":"info","ts":"2023-11-02T13:30:40Z","msg":"updating grype DB","listingURL":"https://toolbox-data.anchore.io/grype/databases/listing.json"}
{"level":"error","ts":"2023-11-02T13:31:40Z","msg":"failed to update grype DB","error":"vulnerability database is invalid (run db update to correct): database metadata not found: /home/nonroot/.cache/grype/db/5"}
{"level":"info","ts":"2023-11-02T13:31:40Z","msg":"restarting to release previous grype DB"}
```

kubevuln can't start correctly. I tried to delete and install with zero, but it doesn't help me.

**Comment by dwertent** [comment]
@batazor An issue occurred during the DB upgrade, and from what I recall, the update disrupted the existing database. I suggest uninstalling and then reinstalling the kubescape-operator.

**Comment by batazor** [comment]
@dwertent This problem is reproduced even when running on a new kubernetes cluster. Restarting kubevuln/storage pods does not solve the problem.

For context: I use ArgoCD for deployment and k8s v1.28.4

**Comment by dwertent** [comment]
@batazor Are you running the latest chart version (1.16.5)?

**Comment by batazor** [comment]
@dwertent Yes, I am using the latest version. Could the problem be related to the fact that _kubescape_ updates any configs that ArgoCD updates to the original version (as one theory)?

**Comment by batazor** [comment]
I disabled `networkPolicy`, and it fixed the problem with running kubescape

```
global:
  networkPolicy:
    enabled: false
    createEgressRules: false
```
