### ISSUE TITLE
Storage retention

### ISSUE THREAD

**Issue by andreyolv** [kubescape/helm-charts#338]
## Overview
I'm using kubescape-operator ,chart version 1.16.0, free plan. At web ui data retention for free plan it's 1 month according to the documentation, but what about storage in Kubernetes?

Is there any way than frequently deleting old data from the storage?

## Problem
Storage always increases and there is no way to automatically delete old records

## Solution
Create retention policy or time to live for storage and add this configuration to helm chart

## Alternatives
None

## Additional context
Image with % of storage PVC usage
![image](https://github.com/kubescape/helm-charts/assets/49295662/2d931aa7-e9e6-45e0-acc0-8888633c9e0b)

**Comment by amirmalka** [comment]
@andreyolv thanks for the feedback!

It looks like a bug. We are looking into this issue and we will keep this issue updated with our findings.

**Comment by matthyx** [comment]
@andreyolv we're working on a cleaning mechanism inside the storage component, it should be ready and merged in the next few days

**Comment by dwertent** [comment]
@andreyolv We [released](https://github.com/kubescape/helm-charts/releases/tag/kubescape-operator-1.16.6) the fix for this issue.

**Comment by amirmalka** [comment]
@andreyolv did you have a chance to try the new version with the fix?

**Comment by andreyolv** [comment]
I haven't tested it yet, I'll test it and get back to you!

**Comment by dwertent** [comment]
[Released](https://github.com/kubescape/helm-charts/releases/tag/kubescape-operator-1.17.2).

**Comment by andreyolv** [comment]
Cleaning it's OK! Thanks!
![image](https://github.com/kubescape/helm-charts/assets/49295662/2f5453ad-d467-4459-b6e7-322e012aa0d9)
