### ISSUE TITLE
Cannot Pull Helm Template

### ISSUE THREAD

**Issue by Ashkaan** [kubescape/helm-charts#369]
# Description
I can't pull a helm template.  We have strict requirements for labels that your chart does not conform to.  We just want to pull the manifests so we can make the adjustments ourselves.

# Environment
OS: `Ubuntu 22.04 LTS`
Version: `1.17.0`
 
# Steps To Reproduce
1. Run
`helm template kubescape kubescape/kubescape-operator -n kubescape --create-namespace --set clusterName='kubectl config current-context' --set account=<removed> --set server=api.armosec.io > armo-helm.yaml --debug`
3. Observe Error

# Expected behavior
A manifest generated.

# Actual Behavior
No manifest and this error:
```
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: /Users/ashkaan/Library/Caches/helm/repository/kubescape-operator-1.17.0.tgz

Error: execution error at (kubescape-operator/templates/operator/registry-scan-recurring-cronjob-configmap.yaml:4:6): `batch/v1/CronJob not supported`
helm.go:84: [debug] execution error at (kubescape-operator/templates/operator/registry-scan-recurring-cronjob-configmap.yaml:4:6): `batch/v1/CronJob not supported`
```

Thanks

**Comment by lucj** [comment]
Got the same thing today :(

**Comment by Ashkaan** [comment]
Thanks for confirming.

**Comment by chrism417** [comment]
I had the same issue. I downloaded the templates locally and changed the occurrences of:
`.Capabilities.APIVersions.Has "batch/v1/CronJob"`
to 
`.Capabilities.APIVersions.Has "batch/v1"`

**Comment by lucj** [comment]
@chrism417 any chance you turn this change into a PR :)

**Comment by chrism417** [comment]
@lucj done, we'll see :)

**Comment by Ashkaan** [comment]
Why is this complete?  I just got the same error.

**Comment by chrism417** [comment]
I'm assuming because it needs to be on the next chart release

**Comment by Ashkaan** [comment]
I might keep this issue open until it's fully resolved, but that's just how I run my devops team.

**Comment by dwertent** [comment]
@Ashkaan We will release a new version in the next hour or two :)
The issue was closed when the PR was merged...

**Comment by dwertent** [comment]
[Released](https://github.com/kubescape/helm-charts/releases/tag/kubescape-operator-1.17.2).
