### ISSUE TITLE
storage pod failing with error

### ISSUE THREAD

**Issue by ld-singh** [kubescape/helm-charts#386]
# Description

The storage pod is failing with below error

panic: runtime error: index out of range [0] with length 0

goroutine 261 [running]:
github.com/olvrng/ujson.Walk({0xc00ab87600, 0x44bb880?, 0x200}, 0xc005db98d8)
	/go/pkg/mod/github.com/olvrng/ujson@v1.1.0/µjson.go:87 +0x990
github.com/kubescape/storage/pkg/cleanup.loadMetadataFromPath({0x2db8240?, 0x44bb880?}, {0xc000a6a1e0, 0x96})
	/work/pkg/cleanup/cleanup.go:144 +0x1fc
github.com/kubescape/storage/pkg/cleanup.(*ResourcesCleanupHandler).StartCleanupTask.func1({0xc000a6a1e0, 0x96}, {0x2da8a68?, 0xc002a6fee0?}, {0x0?, 0x0?})
	/work/pkg/cleanup/cleanup.go:96 +0xfa
github.com/spf13/afero.walk({0x2db8240, 0x44bb880}, {0xc000a6a1e0, 0x96}, {0x2da8a68, 0xc002a6fee0}, 0xc005db9ed0)
	/go/pkg/mod/github.com/spf13/afero@v1.11.0/path.go:44 +0x6c
github.com/spf13/afero.walk({0x2db8240, 0x44bb880}, {0xc00c6dca40, 0x3e}, {0x2da8a68, 0xc00509a4e0}, 0xc005db9ed0)
	/go/pkg/mod/github.com/spf13/afero@v1.11.0/path.go:69 +0x2f4
github.com/spf13/afero.walk({0x2db8240, 0x44bb880}, {0xc00c6dc8c0, 0x34}, {0x2da8a68, 0xc00509a410}, 0xc005db9ed0)
	/go/pkg/mod/github.com/spf13/afero@v1.11.0/path.go:69 +0x2f4
github.com/spf13/afero.Walk({0x2db8240, 0x44bb880}, {0xc00c6dc8c0, 0x34}, 0xc005db9ed0)
	/go/pkg/mod/github.com/spf13/afero@v1.11.0/path.go:105 +0x7a
github.com/kubescape/storage/pkg/cleanup.(*ResourcesCleanupHandler).StartCleanupTask(0xc000b321b0)
	/work/pkg/cleanup/cleanup.go:86 +0x58f
created by main.main in goroutine 1
	/work/main.go:84 +0x6ed

# Environment
OS: `Amazon Linux 2 ` 
Version: `1.18.1 ` 
 
# Steps To Reproduce

# Expected behavior

# Actual Behavior

# Additional context

It is deployed in EKS Cluster

Also seeing these errors in storage pod but these do not fail the container

{"level":"error","ts":"2024-02-01T03:20:25Z","msg":"unmarshal file failed","error":"EOF","path":"/data/spdx.softwarecomposition.kubescape.io/vulnerabilitymanifestsummaries/dummy-namespace/deployment-appt-appt.m"}

**Comment by dwertent** [comment]
Thank you, @ld-singh. We have resolved the issue you mentioned. 
I believe it was resolved in version `1.18.2`. Could you please confirm if the problem no longer occurs for you?

**Comment by dwertent** [comment]
This issue was fixed.
