### ISSUE TITLE
For some reason, the UI is showing that I have an older version chart

### ISSUE THREAD

**Issue by batazor** [kubescape/helm-charts#409]
# Description

I'm using ArgoCD for updates, and have updated the chart many times, but at some point the chart version in the UI stopped updating and I always see the version - v1.17.3

I tried restarting the services, but apparently the result is cached somewhere in the configs?

<img width="683" alt="Screenshot 2024-03-08 at 15 31 05" src="https://github.com/kubescape/helm-charts/assets/1643797/bb9566c8-7370-427b-8dbc-c1d5d0f7c378">

# Environment

k8s 1.29

# Steps To Reproduce

1. Install old chart
2. upgrade to new version

# Expected behavior

correct version in UI

# Actual Behavior

# Additional context

**Comment by dwertent** [comment]
Hi @batazor , are you sure the chart was updated?

Try running:
```
% helm list -n kubescape
NAME     	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                    	APP VERSION
kubescape	kubescape	3       	2024-03-07 10:20:04.083042 +0200 IST	deployed	kubescape-operator-1.18.6	1.18.6
```

**Comment by batazor** [comment]
@dwertent 

I use ArgoCD for installation/updating. And I see that I've the latest version of the images:

<img width="1265" alt="Screenshot 2024-03-13 at 12 48 21" src="https://github.com/kubescape/helm-charts/assets/1643797/f4452766-df08-4ccc-a415-4fe1011c7d6f">

In the end, it's not clear what could have gone wrong.

**Comment by dwertent** [comment]
I noticed you enabled the `release-upgrader` during installation. However, if you are already managing it with argocd, enabling the `release-upgrader` is unnecessary. I think this might be the cause of the issue.

**Comment by batazor** [comment]
Disabled `release-upgrader` so far no results, maybe I should give time to synchronize all data with the cloud.

**Comment by dwertent** [comment]
It should not take more than a few minutes. 
Can you please contact me privately at dwertent@armosec.io so we can take a closer look into it? I would like to investigate based on your `accountID`.

**Comment by yuleib** [comment]
@batazor - hey, do you have more then one cluster installed with this account ?

**Comment by batazor** [comment]
@yuleib I've re-created the cluster a couple of times in the last half a year, but I've used the same servers, so no artifacts should have survived.

Moreover, when I reinstalled kubescape, the metrics stopped coming, so I don't think that could be the reason.

As you can see from the dashboard, there were long phases when I didn't send metrics for various reasons
<img width="1461" alt="Screenshot 2024-03-17 at 15 25 56" src="https://github.com/kubescape/helm-charts/assets/1643797/f5a1ff19-570f-4cc3-8421-aebe2cdd5400">

**Comment by batazor** [comment]
<img width="965" alt="Screenshot 2024-03-17 at 15 29 06" src="https://github.com/kubescape/helm-charts/assets/1643797/6c24316d-76cf-45cc-92b7-2fec4d091162">

And I don't see any other nodes or old resources as part of the cluster

**Comment by Oshratn** [comment]
@batazor first of all sorry for the slow response.
From the screenshots this looks like an ARMO Platform, as such this is not the correct place to get support. Please try reaching via [this link](https://landing.armosec.io/contact-us).
I am aware that there are many things in this support journey that still point to Kubescape and I will get the product team to make the necessary changes.
