### ISSUE TITLE
Storage apiservice attempts to call APIs that were removed in Kubernetes 1.27

### ISSUE THREAD

**Issue by RomanTheLegend** [kubescape/helm-charts#411]
I'm getting an alert in GKE 1.28 cluster that `ksserver` attempts to call this API that's been removed: `/apis/storage.k8s.io/v1beta1/csistoragecapacities`

After removing `csistoragecapacities` resources from `ClusterRole` seems that alert is gone:

https://github.com/kubescape/helm-charts/blob/632f7d66fd0b713a733193ace7cc693e4c08a41a/charts/kubescape-operator/templates/kubescape/clusterrole.yaml#L50

Since `storage.k8s.io` has non-beta API v1 now,  I suspect Storage API has to be updated:
https://github.com/kubescape/helm-charts/blob/632f7d66fd0b713a733193ace7cc693e4c08a41a/charts/kubescape-operator/templates/storage/apiservice.yaml#L14

Specs ref:
https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1/

**Comment by dwertent** [comment]
Thank you @RomanTheLegend for raising this.
@YiscahLevySilas1 I believe we will need to update the version in the control as well.

**Comment by RomanTheLegend** [comment]
@dwertent  Looks like it affects more than just Storage API - `/apis/discovery.k8s.io/v1beta1/endpointslices` is also deprecated
https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/

I think `v1beta1` should be abandoned in more places
