### ISSUE TITLE
Allow hostNetwork for storage deployment

### ISSUE THREAD

**Issue by l-spork-cc** [kubescape/helm-charts#453]
## Overview
Currently the helm chart does not provide the ability to set hostNetwork to true in the storage deployment. Also the port defaults to 443, which might already be in use if hostNetwork is set to true.

## Problem
When using a virtual Network with custom CNIs like Cilium the storage API endpoint is not reachable by the kubeapi server. 

## Solution
Template values to set hostNetwork and port in the helm chart

## Alternatives
None

## Additional context
None

**Comment by matthyx** [comment]
@l-spork-cc we have successfully used kubescape-operator on clusters with Cilium as the CNI, do you have more details to share about the errors you get?

**Comment by matthyx** [comment]
closing for lack of information
