### ISSUE TITLE
In release 1.18.17 during fresh install getting this error " failed to create CustomResourceDefinition serviceauthentication.kubescape.io"

### ISSUE THREAD

**Issue by jagyas** [kubescape/helm-charts#459]
# Description
I was doing a fresh install with version 1.18.17 and I got below error
failed to create CustomResourceDefinition serviceauthentication.kubescape.io: 1 error occurred:
  * CustomResourceDefinition.apiextensions.k8s.io "serviceauthentication.kubescape.io" is invalid: metadata.name: Invalid value: "serviceauthentication.kubescape.io": must be spec.names.plural+"."+spec.group

# Environment
OS: Linux/kubernetes
Version: 3.0.11
 
# Steps To Reproduce
Just do freshh install where you can re install CRDs

# Expected behavior
It should be working fine

# Actual Behavior
Installation failing

**Comment by slashben** [comment]
Can you please retry with `--set capabilities.enableServiceAuth=false` ?

**Comment by matthyx** [comment]
@jagyas we deprecated that API type, please try again with https://github.com/kubescape/helm-charts/releases/tag/kubescape-operator-1.20.5
