### ISSUE TITLE
Problems following the quick start guide

### ISSUE THREAD

**Issue by joaorocha-ceiia** [kubescape/helm-charts#503]
# Description

Using the official [quickstart guide](https://kubescape.io/docs/install-operator/), I followed the steps and the operator pod keeps restarting, outputting this to the logs

```bash
{"level":"fatal","ts":"2024-09-13T15:46:45Z","msg":"open /etc/config/matchingRules.json: no such file or directory","error":"open /etc/config/matchingRules.json: no such file or directory"}
```

Surely there's something that I'm missing, but the guide specifies that it should just work.
For example, running the command

```bash
kubectl get vulnerabilitysummaries
```
doesnt output anything.

# Environment
OS: `Container-Optimized OS from Google ` 
Version: `v1.29.7-gke.1104000 ` 
 
# Steps To Reproduce
1. helm repo add kubescape https://kubescape.github.io/helm-charts/ ; helm repo update ; helm upgrade --install kubescape kubescape/kubescape-operator -n kubescape --create-namespace --set clusterName=`kubectl config current-context` --set capabilities.continuousScan=enable

2. Let every pod settle and check the status of the operator pod

# Expected behavior

The operator pod should work without problems and scan the cluster

# Actual Behavior

Operator pod keeps restarting

**Comment by playworker** [comment]
If you remove `--set capabilities.continuousScan=enable`, this setting seems to have been removed recently but the docs haven't been updated yet
