### ISSUE TITLE
Prometheus Exporter v.0.0.131 not found - helm template defaults to this version

### ISSUE THREAD

**Issue by ulbi** [kubescape/helm-charts#515]
# Description
The current helm template for the prometheus exporter references quay.io/kubescape/prometheus-exporter:v0.0.131, but this version is (no longer?) available. It has been set to v.0.0.-131 six days ago.

# Environment
OS: `Ubuntu 22.04 LTS`
Version: `quay.io/kubescape/kubescape:v3.0.18`
 
# Steps To Reproduce
1. install the helm kubescape-operator - `helm upgrade --install kubescape kubescape/kubescape-operator -n kubescape --create-namespace`
2. Check for the status of the prometheus-exporter pod - it fails to pull the image

# Expected behavior
The image gets pulled

# Actual Behavior
n/a

# Additional context
I set the tag to v.0.0.132 in the values.yaml file I pass to helm.

**Comment by matthyx** [comment]
@ulbi just fixed the tag, sorry
