### ISSUE TITLE
Error pulling kubescape prometheus exporter container image

### ISSUE THREAD

**Issue by joaorocha-ceiia** [kubescape/helm-charts#523]
# Description
When using the latest version of the kubescape operator helm chart (1.22.5), having the prometheusExporter value enabled, i get this error

```
Failed to pull image "quay.io/kubescape/prometheus-exporter:v0.0.131": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/kubescape/prometheus-exporter:v0.0.131": failed to resolve reference "quay.io/kubescape/prometheus-exporter:v0.0.131": quay.io/kubescape/prometheus-exporter:v0.0.131: not found
```

# Environment
OS: `Container-Optimized OS from Google ` 
Version: ` 1.22.5 (helm chart version) ` 
 
# Steps To Reproduce
1. 
```
helm repo add kubescape https://kubescape.github.io/helm-charts/

helm repo update

helm upgrade \
  --install \
  kubescape kubescape/kubescape-operator \
  -n kubescape \
  --create-namespace \
  --set clusterName=`kubectl config current-context` \
  --set capabilities.continuousScan=enable \
  --set capabilities.prometheusExporter=enable
```

2. kubectl get pods -n kubescape
3. Check the status of the prometheus-exporter pod

# Expected behavior
The Prometheus Exporter container image should be available and pulled with success.

# Actual Behavior
The Prometheus Exporter container image can't be downloaded, giving an error that the tag doesnt exist.

# Additional context

**Comment by matthyx** [comment]
hi @joaorocha-ceiia I've fixed the tag... looks like our github action to release has some issues, thanks for reporting!
